### ISSUE TITLE
script doesn't check for tool availability

### ISSUE THREAD

**Issue by laf0rge** [Monkeycat-nl/APUFirmware#2]
It would be best to check if flashrom and/or other tools like  dmidecode are actually available/installed before blindly trying to execute them.  If they don't exist, I would suggest to print meaningful error messages asking the user to install those tools first.

**Comment by laf0rge** [comment]
wget is another such tool.

**Comment by Monkeycat-nl** [comment]
i have no idea how to check that... (lots of distros different methods).
Will append it to the readme that you need wget and dmidecode installed prior to running this.

**Comment by laf0rge** [comment]
thanks for the README. 

You could also have a few lines at the start of the script whihc tries to execute the tools and check for exit code / $? and print a message that tool X/Y/Z could not be found.

But yes, it's a mere cosmetic improvement which would render a nice error message, nothing critical.

**Comment by Monkeycat-nl** [comment]
yeah did not think about that, now it does check :-)

**Comment by laf0rge** [comment]
thanks. for the record: fix is in 016fed07a8747fae3498120c73b10662c9dbd3fd

**Comment by Monkeycat-nl** [comment]
did some more cosmetic improvement
I sprinkled comments into the source
added beter reboot method

anyway... two happy users!

but also sad news...
[https://docs.dasharo.com/variants/pc_engines/post-eol-fw-announcement/](https://docs.dasharo.com/variants/pc_engines/post-eol-fw-announcement/) 👎
